### ISSUE TITLE
Create secret for image pull from nexus

### ISSUE THREAD

**Issue by fsadykov** [fuchicorp/common_tools#91]
Hello team,

Please create secret `nexus-creds` to pull docker images from our nexus. We should be able to pull images using that secret. see bellow example. 

```
spec:
  containers:
  - image: docker.fuchicorp.com/website-prod:0.6
    imagePullPolicy: IfNotPresent
    name: website
  imagePullSecrets:
  - name: nexus-creds
```

**Actions**
1. Create a terraform code to create this secret
2. Create PR for this feature
